### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by oeriksen** [gjohansson-ST/yale_smart_alarm#1]
I'm trying to use/test this but I'm getting an error trying to setup.
I've copied the yale_smart_alarm folder into custom_components, restarted and add integration but I'm getting the following error messages:
I've tried a couple of times but I'm getting the same messages each time.

`2021-05-23 16:25:03 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform yale_smart_alarm.alarm_control_panel: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).`

`2021-05-23 16:25:03 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform yale_smart_alarm.lock: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).`

`2021-05-23 16:25:03 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform yale_smart_alarm.binary_sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).`

**Comment by gjohansson-ST** [comment]
Upgrade your HA to 2021.05 (DeviceInfo was not implemented before it looks like)
Let me know if that helps

**Comment by oeriksen** [comment]
I'm running 2021.05.5 (latest).

**Comment by gjohansson-ST** [comment]
You're right. Apparently not yet implemented in core.
I have reversed to mapping instead so download it again and give it a try.
I am running this into the official component so have myself only been running this in dev.

**Comment by oeriksen** [comment]
You forgot to remove DeviceInfo imports:

https://github.com/gjohansson-ST/yale_smart_alarm/blob/eec08869caa578557fd6457152f961f34ab2e5e2/custom_components/yale_smart_alarm/alarm_control_panel.py#L29

https://github.com/gjohansson-ST/yale_smart_alarm/blob/eec08869caa578557fd6457152f961f34ab2e5e2/custom_components/yale_smart_alarm/binary_sensor.py#L7

https://github.com/gjohansson-ST/yale_smart_alarm/blob/eec08869caa578557fd6457152f961f34ab2e5e2/custom_components/yale_smart_alarm/lock.py#L13

After removing those it seems to work perfectly. I've just testet unlocking and locking the door and arming and disarming the alarm.

But it seems there are another issue. It's impossible to setup (add integration) without supplying the (door) code. Even though, after looking at the code, it should be optional. The error message is gone from my log after a reboot but I can recreate it if you want.

Looking forward to this being merged into the official component. Thank you for your work!

**Comment by gjohansson-ST** [comment]
Thanks. The official PR (only alarm) has quite a few more adds than this custom.
https://github.com/home-assistant/core/pull/50850
You might want to give it a 👍 to get it moving faster.

Btw: Would appreciate a report on the error for the door code as yes, it should be optional.

Thanks

**Comment by oeriksen** [comment]
Did give the PR a :+1: 

In the gui I get the following message: Unknown error occurred
The log message and stacktrace is attached.

[home-assistant.log](https://github.com/gjohansson-ST/yale_smart_alarm/files/6533672/home-assistant.log)

**Comment by gjohansson-ST** [comment]
Thanks. I believe it's now corrected so a code is not necessary.
Eventually in the official this will go into options anyhow. This custom is quite behind in dev but ok to use until official has been approved

**Comment by oeriksen** [comment]
I checked the Home Assistant logs today I find that they are full of these messages:

`
2021-06-10 21:09:02 ERROR (SyncWorker_7) [backoff] Giving up _authorize(...) after 8 tries (requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mob.yalehomesystem.co.uk/yapi/yapi/o/token/)
`

`
2021-06-10 21:09:02 INFO (SyncWorker_7) [backoff] Backing off get_authenticated(...) for 0.1s (requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mob.yalehomesystem.co.uk/yapi/yapi/o/token/)
`

`
2021-06-10 21:09:03 INFO (SyncWorker_7) [backoff] Backing off _authorize(...) for 0.7s (requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mob.yalehomesystem.co.uk/yapi/yapi/o/token/)
`

So far over 180.000 lines :smile:
I'm removing/deactivating for now.

**Comment by gjohansson-ST** [comment]
> So far over 180.000 lines 😄
> I'm removing/deactivating for now.

Wow... That is some log-file then 😅 
Apparently I had not updated it to the latest package version where this is addressed. I have now done so if you want to give it another try.

**Comment by oeriksen** [comment]
I've been using it for a couple of days now and only a handful of messages in the log so seems good so far. Thank you!
